function topMenuScrollShadow(){var scrollTop=window.pageYOffset;var topMenu=document.querySelector('.top-menu');window.addEventListener('scroll',function(){scrollTop=window.pageYOffset;if(scrollTop>=20){topMenu.classList.add('highlight');}
if(scrollTop<20){topMenu.classList.remove('highlight');}});}
function hexToRgb(hex){return hex.replace(/^#?([a-f\d])([a-f\d])([a-f\d])$/i,function(m,r,g,b){return '#'+r+r+g+g+b+b;}).substring(1).match(/.{2}/g).map(function(x){return parseInt(x,16);});}
var hexDigits=new Array("0","1","2","3","4","5","6","7","8","9","a","b","c","d","e","f");function rgb2hex(rgb){rgb=rgb.match(/^rgb\((\d+),\s*(\d+),\s*(\d+)\)$/);return "#"+hex(rgb[1])+hex(rgb[2])+hex(rgb[3]);}
function hex(x){return isNaN(x)?"00":hexDigits[(x-x%16)/16]+hexDigits[x%16];}
function copyColors(){var aioColors=document.querySelectorAll('.active-palette p');aioColors.forEach(function(color){color.addEventListener('click',function(){var selection=window.getSelection();var range=document.createRange();range.selectNodeContents(color);selection.removeAllRanges();selection.addRange(range);try{(function(){document.execCommand('copy');selection.removeAllRanges();var original=color.textContent;color.textContent='Copied!';color.classList.add('success');setTimeout(function(){color.textContent=original;color.classList.remove('success');},1200);})();}catch(e){(function(){var errorMsg=document.querySelector('.error-msg');errorMsg.classList.add('show');setTimeout(function(){errorMsg.classList.remove('show');},1200);})();}});});}
function showColorPalette(){var colorPalette=document.querySelectorAll('.palette-colors');var sideBar=document.querySelector('.side-menu');for(var i=0;i<colorPalette.length;i++){colorPalette[i].addEventListener('click',function(){var activePalette=document.querySelector('.active-palette');var activePaletteId=this.id;sideBar.classList.add('active');activePalette.innerHTML='';activePalette.classList.add('active');activePalette.id=activePaletteId;for(var i=0;i<this.childNodes.length;i++){if(i===1||i===3||i===5||i===7){var colorBox=document.createElement('div');var colorObject=document.createElement('div');var colorText=document.createElement("p");var colorTextRGB=document.createElement("p");colorBox.className='color';colorObject.className='active-color';colorObject.style.background="#"+this.childNodes[i].id;colorText.className='active-color-text';colorText.innerHTML="#"+this.childNodes[i].id;colorTextRGB.className='active-color-text-RGB';colorTextRGB.innerHTML="rgba("+hexToRgb("#"+this.childNodes[i].id)+(",1)");colorBox.appendChild(colorObject);colorBox.appendChild(colorText);colorBox.appendChild(colorTextRGB);activePalette.appendChild(colorBox);}}
var errorBox=document.createElement('div');errorBox.className='error-msg';errorBox.innerHTML='Can\'t copy, hit Ctrl+C!';activePalette.appendChild(errorBox);copyColors();});}}
function closeSideBar(){var sideBarClose=document.querySelector('.side-menu');sideBarClose.classList.remove('active');}
document.addEventListener('keyup',function(e){if(e.keyCode===27){closeSideBar();}});function backgroundSwitcher(){var bodyElement=document.querySelector('body');var bgColorMenu=document.querySelector('.bg-color-menu');var colors=bgColorMenu.querySelectorAll('.color');for(var i=0;i<colors.length;i++){colors[i].addEventListener('click',function(){if(this.id==='black'){bodyElement.style.background='#333333';localStorage.setItem('bgColor','#333333');}else if(this.id==='white'){bodyElement.style.background='#ffffff';localStorage.setItem('bgColor','#ffffff');}else if(this.id==='red'){bodyElement.style.background='#f94032';localStorage.setItem('bgColor','#f94032');}else if(this.id==='green'){bodyElement.style.background='#11CD86';localStorage.setItem('bgColor','#11CD86');}else if(this.id==='blue'){bodyElement.style.background='#00A0FF';localStorage.setItem('bgColor','#00A0FF');}else if(this.id==='yellow'){bodyElement.style.background='#f9c00c';localStorage.setItem('bgColor','#f9c00c');}else if(this.id==='blueGradient'){bodyElement.style.background='linear-gradient(to right, #4facfe 0%, #00f2fe 100%)';localStorage.setItem('bgColor','linear-gradient(to right, #4facfe 0%, #00f2fe 100%)');}else if(this.id==='greenGradient'){bodyElement.style.background='linear-gradient(to right, #43e97b 0%, #38f9d7 100%)';localStorage.setItem('bgColor','linear-gradient(to right, #43e97b 0%, #38f9d7 100%)');}else if(this.id==='sunset'){bodyElement.style.background='linear-gradient(to right, #fa709a 0%, #fee140 100%)';localStorage.setItem('bgColor','linear-gradient(to right, #fa709a 0%, #fee140 100%)');}else if(this.id==='starWine'){bodyElement.style.background='linear-gradient(to right, #b8cbb8 0%, #b8cbb8 0%, #b465da 0%, #cf6cc9 33%, #ee609c 66%, #ee609c 100%)';localStorage.setItem('bgColor','linear-gradient(to right, #b8cbb8 0%, #b8cbb8 0%, #b465da 0%, #cf6cc9 33%, #ee609c 66%, #ee609c 100%)');}else if(this.id==='snow'){bodyElement.style.background='linear-gradient(to right, #e6e9f0 0%, #eef1f5 100%)';localStorage.setItem('bgColor','linear-gradient(to right, #e6e9f0 0%, #eef1f5 100%)');}else if(this.id==='matrix'){bodyElement.style.background='linear-gradient(to right, #fcc5e4 0%, #fda34b 15%, #ff7882 35%, #c8699e 52%, #7046aa 71%, #0c1db8 87%, #020f75 100%)';localStorage.setItem('bgColor','linear-gradient(to right, #fcc5e4 0%, #fda34b 15%, #ff7882 35%, #c8699e 52%, #7046aa 71%, #0c1db8 87%, #020f75 100%)');}});}}
function setBackgroundColor(){var bgColor=localStorage.getItem('bgColor');var bodyElement=document.querySelector('body');bodyElement.style.background=bgColor;}
function getColorsFromImage(imgPath){var img=document.createElement('img');var sideBarContainer=document.querySelector('.active-palette');var color;var activeColor;var activeColorText;var activeColorTextRGB;sideBarContainer.innerHTML='';img.setAttribute('src',imgPath);img.addEventListener('load',function(){var vibrant=new Vibrant(img,64,1);var swatches=vibrant.swatches();for(var swatch in swatches){if(swatches.hasOwnProperty(swatch)&&swatches[swatch]){console.log(swatch,swatches[swatch].getHex());color=document.createElement('div');activeColor=document.createElement('div');activeColorText=document.createElement('p');activeColorTextRGB=document.createElement('p');color.classList.add('color');color.setAttribute('title',swatch);activeColor.classList.add('active-color');activeColorText.classList.add('active-color-text');activeColorTextRGB.classList.add('active-color-text-RGB');activeColor.style.background=swatches[swatch].getHex();activeColorText.innerHTML=swatches[swatch].getHex();activeColorTextRGB.innerHTML="rgba("+hexToRgb(swatches[swatch].getHex())+(",1)");color.appendChild(activeColor);color.appendChild(activeColorText);color.appendChild(activeColorTextRGB);sideBarContainer.classList.add('active');sideBarContainer.classList.add('scan');sideBarContainer.appendChild(color);copyColors();}}});setTimeout(function(){$.ajax({type:"POST",url:"/clear-uploads.php",data:{},beforeSend:function(xhr){console.log("Processing image, please wait...");},error:function(qXHR,textStatus,errorThrow){console.log("There was an error handeling the image");},success:function(data,textStatus,jqXHR){console.log('Image successfully processed');}});},2000);}
function dropzoneUploader(){var sideBar=document.querySelector('.side-menu');Dropzone.autoDiscover=true;Dropzone.options.dropzoneForm={url:"/upload.php",renameFilename:function(filename){return new Date().getTime()+'_'+filename;},init:function(){this.on("success",function(file){var imgPath="/uploads/"+file.upload.filename;getColorsFromImage(imgPath);sideBar.classList.add('active');});}};}
function like(){var form=$('.like-form');form.submit(function(e){e.preventDefault();var thisLikes=this.querySelector('#current-likes').value;var thisId=this.querySelector('#palette-id').value;var thisCounter=this.querySelector('.likes-count');var thisLikeButton=this.querySelector('.likes');var formData={'id':thisId,'current-likes':thisLikes};$.ajax({type:'POST',url:'/likes.php',data:formData,dataType:'json',encode:true}).done(function(data){console.log(data.message);thisCounter.innerHTML=data.message;thisLikeButton.classList.add('liked');localStorage.setItem(thisId,thisId);});});}
function likeHightlight(){var colorPalette=document.querySelectorAll('.palette');var likeArray=[];for(var key in localStorage){likeArray.push(key);}
for(var i=0;i<colorPalette.length;i++){if(likeArray.includes(colorPalette[i].id)){var currentLikeButton=colorPalette[i].querySelector('.likes');currentLikeButton.classList.add('liked');currentLikeButton.disabled=true;}}}
function displayFlatColor(){var flatColor=document.querySelectorAll('.flat');var sideBar=document.querySelector('.side-menu');var sideBarText=sideBar.querySelector('.color-msg');for(var i=0;i<flatColor.length;i++){flatColor[i].addEventListener('click',function(){var selectedColor=this.style.backgroundColor;sideBarText.style.color="grey";sideBarText.innerHTML=selectedColor+"<br><br>"+rgb2hex(selectedColor);});}}
function closeAd(){var adContainer=document.querySelector('.ad');var adCloseButton=adContainer.querySelector('.close-button');adCloseButton.addEventListener('click',function(){adContainer.classList.add('closed');});}
function darkmode(){var toggleButton=document.querySelector('.darkmode');var bodyElement=document.querySelector('body');var darkmodeSetting=localStorage.getItem('darkmode');if(darkmodeSetting==="1"){bodyElement.classList.add('dark');toggleButton.innerHTML="Light Mode";}
toggleButton.addEventListener('click',function(){if(bodyElement.classList.contains('dark')){bodyElement.style.background='#ffffff';localStorage.setItem('bgColor','#ffffff');bodyElement.classList.remove('dark');localStorage.setItem('darkmode','0');toggleButton.innerHTML="Dark Mode";}
else{bodyElement.classList.add('dark');bodyElement.style.background='#333333';localStorage.setItem('bgColor','#333333');localStorage.setItem('darkmode','1');toggleButton.innerHTML="Light Mode";}});}
function showliked(e){var showLikeButton=document.querySelector('.showing');if(showLikeButton===null){e.target.parentElement.parentElement.classList.add('showing');var likePalettes=document.querySelectorAll('button.likes');for(var i=0;i<likePalettes.length;i++){if(likePalettes[i].classList.contains('liked')===false){likePalettes[i].parentElement.parentElement.style.display='none';}}}else{showLikeButton.classList.remove('showing');var colorPalette=document.querySelectorAll('.likes');for(var i=0;i<colorPalette.length;i++){colorPalette[i].parentElement.parentElement.style.display='block';}}}
likeHightlight();darkmode();setBackgroundColor();topMenuScrollShadow();showColorPalette();backgroundSwitcher();closeAd();like();